//! Neo4j Cypher export. Ports `export.py::to_cypher`, `_cypher_escape`,
//! `_cypher_label`. One MERGE per node, one MATCH+MERGE per edge; ids and
//! string values are escaped for single-quoted literals, and identifier-position
//! values (node label / rel type) are allowlisted to `[A-Za-z0-9_]`.

use crate::{attr_str, node_id, Graph};

/// Escape a string for a single-quoted Cypher literal (F-008). Drops C0 control
/// bytes except tab, then escapes `\`, `'`, newline, CR.
fn cypher_escape(s: &str) -> String {
    let cleaned: String = s.chars().filter(|&c| c >= ' ' || c == '\t').collect();
    cleaned
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

/// Sanitise a value used in identifier position (label / rel type): strip all
/// but `[A-Za-z0-9_]`, require a leading letter, else fall back to a constant.
fn cypher_label(raw: &str, fallback: &str) -> String {
    let cleaned: String = raw.chars().filter(|c| c.is_ascii_alphanumeric() || *c == '_').collect();
    match cleaned.chars().next() {
        Some(c) if c.is_ascii_alphabetic() => cleaned,
        _ => fallback.to_string(),
    }
}

/// Python `str.capitalize()`: first char upper, the rest lower.
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase(),
    }
}

pub fn to_cypher(g: &Graph) -> String {
    let mut lines: Vec<String> = vec![
        "// Neo4j Cypher import - generated by atlas".to_string(),
        String::new(),
    ];

    for n in &g.nodes {
        let id = node_id(n);
        let label = cypher_escape(attr_str(n, "label").unwrap_or(id));
        let id_esc = cypher_escape(id);
        let ftype_raw = attr_str(n, "file_type").filter(|s| !s.is_empty()).unwrap_or("unknown");
        let ftype = cypher_label(&capitalize(ftype_raw), "Entity");
        lines.push(format!(
            "MERGE (n:{ftype} {{id: '{id_esc}', label: '{label}'}});"
        ));
    }
    lines.push(String::new());

    for e in &g.links {
        let u = attr_str(e, "source").unwrap_or("");
        let v = attr_str(e, "target").unwrap_or("");
        let rel_raw = attr_str(e, "relation").filter(|s| !s.is_empty()).unwrap_or("RELATES_TO");
        let rel = cypher_label(&rel_raw.to_uppercase(), "RELATES_TO");
        let conf = cypher_escape(attr_str(e, "confidence").unwrap_or("EXTRACTED"));
        let u_esc = cypher_escape(u);
        let v_esc = cypher_escape(v);
        lines.push(format!(
            "MATCH (a {{id: '{u_esc}'}}), (b {{id: '{v_esc}'}}) \
             MERGE (a)-[:{rel} {{confidence: '{conf}'}}]->(b);"
        ));
    }

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use crate::httpx;

    #[test]
    fn one_statement_per_node_and_edge() {
        let g = httpx();
        let cy = super::to_cypher(&g);
        assert_eq!(cy.matches("MERGE (n:").count(), g.nodes.len());
        assert_eq!(cy.matches("MATCH (a {id:").count(), g.links.len());
        // every statement is `;`-terminated
        assert_eq!(cy.matches(");").count(), g.nodes.len() + g.links.len());
    }

    #[test]
    fn ids_are_escaped_and_rel_types_allowlisted() {
        // A hostile id with a quote and newline must not break out.
        let g = atlas_core::Graph::from_json_str(
            r#"{"nodes":[{"id":"a'b\nc","label":"L'X"}],
                "links":[{"source":"a'b\nc","target":"a'b\nc","relation":"calls; DROP","confidence":"EXTRACTED"}]}"#,
        )
        .unwrap();
        let cy = super::to_cypher(&g);
        // control chars (the newline) are stripped first, then the quote escaped
        assert!(cy.contains("id: 'a\\'bc'"));
        // rel type stripped to allowlist — no stray "; DROP" injected as Cypher
        assert!(cy.contains("[:CALLSDROP {"));
        assert!(!cy.contains("DROP;"));
    }
}
